@GuessWordApi_HostAddress = http://localhost:5114

### Проверка работы API через Swagger
GET {{GuessWordApi_HostAddress}}/swagger/index.html
Accept: text/html

###

### Пример: старт игры
GET {{GuessWordApi_HostAddress}}/start?user=Aliaksandr
Accept: application/json

###

### Пример: попытка угадать букву
POST {{GuessWordApi_HostAddress}}/guess
Content-Type: application/json

{
  "user": "Aliaksandr",
  "letter": "A"
}

###

### Пример: статус игры
GET {{GuessWordApi_HostAddress}}/status?user=Aliaksandr
Accept: application/json

